### ISSUE TITLE
疑問 : [設定當前環境中的變數]

### ISSUE THREAD

**Issue by wibe01204** [Nat1anWasTaken/Lava#17]
教學中的第三點，因為不是本科生，因為找不到所以不確定要到哪邊設定
目前是想用win11架設，感謝~
`附圖`
![image](https://user-images.githubusercontent.com/90883053/233797616-0d5c8bcd-f6b8-4ac1-8098-b6b4cd9e97b6.png)

**Comment by Nat1anWasTaken** [comment]
你可以在機器人的目錄創建一個 `.env` 檔案，記住 `.env` 就是檔案名，不是副檔名

檔案內容
```
TOKEN=
SPOTIFY_CLIENT_ID=
SPOTIFY_CLIENT_SECRET=
SPOTIPY_REDIRECT_URI=
```

將你的資料填入等號後方應該就可以了！

**Comment by wibe01204** [comment]
解決了! 感謝~~
