### ISSUE TITLE
feat: search menu after /play command

### ISSUE THREAD

**Issue by ThomasPlum** [Nat1anWasTaken/Lava#28]
**你的功能請求與問題有關嗎？請描述**
因為使用手機版或是電腦版的時候斜線指令./play常常會沒有選到自動填入的內容導致說整個名稱需要重新輸入

**描述你想要的解決方案**
我希望如果沒有選到送出的時候能夠使用文字的方式來做一個下拉選單讓使用者能夠二次選擇

**描述你考慮過的替代方案**
或是可以把搜尋結果條列出來使用按鈕的方式選擇

**其他內容**
像是yeecord的機器龍

**Comment by Mantou-9487** [comment]
感謝你的建議！我會找時間實作此功能
